### ISSUE TITLE
Weird Â letters appearing on the text

### ISSUE THREAD

**Issue by dresatt** [GladistonXD/html2pdfconverter#1]
Hello, I've used your Perlego downloader successfully and i've been satisfied enough to study the book from the html.

I saw your html to pdf converted and I successfully tried it out. My first pdf produced, there aren't any pictures, the text isn't centered and there are wrong page cutoffs which I understand may have been my mistake. However, there are these weird Â letters appearing all of the text that obscure it. Do you know how to fix this? Thank you
[perlegotest.pdf](https://github.com/user-attachments/files/17512807/perlegotest.pdf)

**Comment by GladistonXD** [comment]
Could you send the .html file? It seems to be a coding problem.

**Comment by dresatt** [comment]
Apparently I can't send it to this issue section for some reason. The file is greyed out and I can't click it.

I've uploaded it to my repository. I hope that is satisfactory.

**Comment by GladistonXD** [comment]
The problem is that this script only works with `EPUB` book formats, PDF formats use SVG images, hence the confusion when printing, in this case you can only use the browser itself to print the content in PDF.

**Comment by dresatt** [comment]
Hello. I seem to have fixed the problem myself. Encoding it in UTF-8 seemed to have worked. Pictures can load when cairosvg is implemented and the shifting can be fixed with changing the margin (by trial and error). Thanks for creating the perlego downloader and html2pdf converter, really helped!

**Comment by GladistonXD** [comment]
Very good, if you want to share the code to help if someone is having the same problem it will be useful.
